name: Check for broken links

on:
  push:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"
  pull_request:
    branches:
      - master
      - main
    paths:
      - "assets/**"
      - "**.html"
      - "**.js"
      - "**.liquid"
      - "**/*.md"
      - "**.yml"
      - "!.github/workflows/axe.yml"
      - "!.github/workflows/deploy-docker-tag.yml"
      - "!.github/workflows/deploy-image.yml"
      - "!.github/workflows/docker-slim.yml"
      - "!.github/workflows/lighthouse-badger.yml"
      - "!.github/workflows/prettier.yml"
      - "!lighthouse_results/**"

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v2.1.0
        with:
          fail: true
          args: >-
            --user-agent 'curl/7.54'
            --exclude-path FAQ.md
            --exclude-path README.md
            --exclude-path CUSTOMIZE.md
            --exclude-path _pages/404.md
            --exclude-path _posts/
            --exclude-path _books/
            --exclude="^https?://(www\.)?cell\.com($|/.*)"
            --exclude="^https?://(www\.)?sciencedirect\.com($|/.*)"
            --exclude="^https?://(www\.)?science\.org($|/.*)"
            --exclude="^https?://(www\.)?academic\.oup\.com($|/.*)"
            --exclude="^https?://(www\.)?biorxiv\.org($|/.*)"
            --exclude="^https?://(www\.)?authors\.elsevier\.com($|/.*)"
            --exclude="^https?://(www\.)?doi\.org($|/.*)"
            --exclude="^https?://(www\.)?scholar\.google\..*"
            --exclude="^https?://(www\.)?simonsfoundation\.org/.*"
            --verbose
            --no-progress
            './**/*.md'
            './**/*.html'
